name: Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
      - develop
    pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ASSETS_FOLDER: USharpVideoSubtitles
      UNITYPACKAGE: USharpVideoSubtitles_${{ github.ref_name }}.unitypackage
    steps:
    - uses: actions/checkout@v3

    - uses: metcalfc/changelog-generator@v3.0.0
      id: changelog
      if: startsWith(github.ref, 'refs/tags/')
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        rm -fr "Assets/${{ env.ASSETS_FOLDER }}/Development"
        echo "Assets/${{ env.ASSETS_FOLDER }}.meta" > metaList
        find "Assets/${{ env.ASSETS_FOLDER }}/" -name \*.meta >> metaList

    - run: |
        echo "$GITHUB_REF_NAME" > "Assets/${{ env.ASSETS_FOLDER }}/version.txt"
        sed -i -e "s/(dev version)/$GITHUB_REF_NAME/g" "Assets/${{ env.ASSETS_FOLDER }}/Subtitles.prefab"
      if: startsWith(github.ref, 'refs/tags/')

    - run: |
        VERSION=$GITHUB_REF_NAME-$(git rev-parse --short "$GITHUB_SHA")
        echo "$VERSION" > "Assets/${{ env.ASSETS_FOLDER }}/version.txt"
        sed -i -e "s/(dev version)/$VERSION/g" "Assets/${{ env.ASSETS_FOLDER }}/Subtitles.prefab"
      if: startsWith(github.ref, 'refs/heads/')

    - uses: pCYSl5EDgo/create-unitypackage@v1
      with:
        package-path: ${{ env.UNITYPACKAGE }}
        include-files: metaList

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: ${{ steps.changelog.outputs.changelog }}
        files: ${{ env.UNITYPACKAGE }}
        draft: true

    - uses: actions/upload-artifact@v3
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        name: ${{ env.UNITYPACKAGE }}
        path: ${{ env.UNITYPACKAGE }}
