name: Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "**"
  workflow_dispatch:

env:
  PACKAGE_NAME: USharpVideoSubtitles

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      version: ${{ steps.variables.outputs.version }}
      unitypackage_file: ${{ steps.variables.outputs.unitypackage_file }}

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history needed for 'git describe' below

      - name: Set needed variables
        id: variables
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags/.* ]]; then
              version="$GITHUB_REF_NAME"
          else
              version="$(git describe --tags --always)"
          fi
          echo "version=$(echo "$version" | sed 's/^v//')" >> $GITHUB_OUTPUT
          echo "unitypackage_file=${{ env.PACKAGE_NAME }}-${version}.unitypackage" >> $GITHUB_OUTPUT
          cat "$GITHUB_OUTPUT"

      - name: Insert version string to files
        run: |
          placeholder="0.0.0-dev"
          version="${{ steps.variables.outputs.version }}"
          grep -rlF "$placeholder" "Assets/${{ env.PACKAGE_NAME }}/" | while IFS= read -r file; do
              echo "$file"
              sed "s|$placeholder|$version|g" -i "$file"
          done

      - name: Generate list of meta files
        run: |
          echo "Assets/${{ env.PACKAGE_NAME }}.meta" > metaList
          find "Assets/${{ env.PACKAGE_NAME }}/" -name \*.meta >> metaList

      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@v1
        with:
          package-path: ${{ steps.variables.outputs.unitypackage_file }}
          include-files: metaList

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ needs.build.outputs.unitypackage_file }}
          generate_release_notes: true
          draft: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: build
          path: |
            ${{ steps.variables.outputs.unitypackage_file }}
