name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
      - develop
  workflow_dispatch:

env:
  PACKAGE_NAME: USharpVideoSubtitles

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject version number
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags/.* ]]; then
              version="$(echo "$GITHUB_REF_NAME" | sed 's/^v//')"
          else
              version="${GITHUB_REF_NAME}-$(git rev-parse --short "$GITHUB_SHA")"
          fi
          echo "$version" > "Assets/${{ env.PACKAGE_NAME }}/version.txt"
          sed -i -e "s/(dev version)/$version/g" "Assets/${{ env.PACKAGE_NAME }}/Subtitles.prefab"

      - name: Do not include Development folder
        run: rm -fr "Assets/${{ env.PACKAGE_NAME }}/Development" "Assets/${{ env.PACKAGE_NAME }}/Development.meta"

      - name: Generate list of meta files
        run: |
          echo "Assets/${{ env.PACKAGE_NAME }}.meta" > metaList
          find "Assets/${{ env.PACKAGE_NAME }}/" -name \*.meta >> metaList

      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@v1
        with:
          package-path: ${{ env.PACKAGE_NAME }}_${{ github.ref_name }}.unitypackage
          include-files: metaList

      - name: Generate changelog
        uses: metcalfc/changelog-generator@v4
        id: changelog
        if: startsWith(github.ref, 'refs/tags/')
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          files: |
            ${{ env.PACKAGE_NAME }}_${{ github.ref_name }}.unitypackage
          draft: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          path: ${{ env.PACKAGE_NAME }}_${{ github.ref_name }}.unitypackage
